name: flutter_bloc_architecture
description: A new Flutter bloc arichitecture application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^5.0.0
  equatable: ^1.2.0
  flutter_hooks: ^0.11.0
  flutter_translate: ^1.6.0
  flutter_localizations:
    sdk: flutter
  flutter_translate_annotations: ^1.0.1
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_translate_gen: ^1.2.4
  build_runner:
  freezed:

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
